# Generated by Django 4.1.7 on 2023-03-29 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uchet', '0002_journal_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='date_rep',
            field=models.DateField(blank=True),
        ),
    ]
