# Generated by Django 4.1.7 on 2023-03-29 21:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uchet', '0003_alter_journal_date_rep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='date_rep',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 3, 30, 0, 5, 59, 693683)),
        ),
    ]
