# Generated by Django 4.1.7 on 2023-03-18 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_alter_car_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=25, verbose_name='Тип погрузчика')),
                ('inn', models.PositiveSmallIntegerField(unique=True, verbose_name='Инвентарный номер')),
                ('sn', models.CharField(max_length=15, unique=True, verbose_name='Заводской номер')),
                ('dateofpurchase', models.DateField(verbose_name='Дата приобретения')),
                ('dateofpurchaseakb', models.DateField(verbose_name='Дата приобретения')),
                ('snakb', models.CharField(max_length=15, unique=True, verbose_name='Серийный номер АКБ')),
                ('gsakb', models.DateField(verbose_name='Гарантия АКБ до')),
            ],
        ),
    ]
