# Generated by Django 4.1.7 on 2023-03-19 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kindofoperation', models.CharField(max_length=20, verbose_name='Вид операции')),
                ('dateoperation', models.DateTimeField(verbose_name='Дата операции')),
                ('driver', models.CharField(max_length=20, verbose_name='ФИО')),
                ('stateout', models.CharField(max_length=20, verbose_name='Неисправности')),
                ('running', models.SmallIntegerField(verbose_name='Наработка')),
                ('charge', models.BooleanField(verbose_name='Зарядка')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hello.card')),
            ],
        ),
    ]
