# Generated by Django 4.1.7 on 2023-03-20 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_routesheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routesheet',
            name='charge',
            field=models.CharField(max_length=20, verbose_name='Зарядка'),
        ),
    ]
