# Generated by Django 4.1.7 on 2023-03-20 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0007_remove_routesheet_charge_remove_routesheet_driver_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routesheet',
            name='card',
        ),
    ]
