# Generated by Django 4.1.7 on 2023-03-20 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0008_remove_routesheet_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='routesheet',
            name='driver',
            field=models.CharField(default='ooo', max_length=20),
        ),
    ]
