# Generated by Django 4.1.7 on 2023-03-20 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0010_routesheet_card_alter_routesheet_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='routesheet',
            name='dateoperation',
            field=models.DateTimeField(null=True, verbose_name='Дата операции'),
        ),
    ]
