# Generated by Django 4.1.7 on 2023-03-20 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0011_routesheet_dateoperation'),
    ]

    operations = [
        migrations.AddField(
            model_name='routesheet',
            name='charge',
            field=models.CharField(max_length=20, null=True, verbose_name='Зарядка'),
        ),
        migrations.AddField(
            model_name='routesheet',
            name='kindofoperation',
            field=models.CharField(max_length=20, null=True, verbose_name='Вид операции'),
        ),
        migrations.AddField(
            model_name='routesheet',
            name='running',
            field=models.SmallIntegerField(null=True, verbose_name='Наработка'),
        ),
        migrations.AddField(
            model_name='routesheet',
            name='stateout',
            field=models.CharField(max_length=20, null=True, verbose_name='Неисправности'),
        ),
    ]
